# Generated by Django 2.0.3 on 2018-08-22 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genomic_file',
            fields=[
                ('id_genomic_file', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=200)),
                ('upload', models.FileField(upload_to='uploads/')),
                ('tp_file', models.CharField(max_length=5)),
                ('tax_id', models.CharField(blank=True, max_length=30)),
                ('host', models.CharField(blank=True, max_length=50)),
                ('isolation_source', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id_tool', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.FilePathField()),
                ('tool_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('tp_tool', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tool_request',
            fields=[
                ('id_request', models.IntegerField(primary_key=True, serialize=False)),
                ('input_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamira_platform.Genomic_file', verbose_name='the uploaded genomic file by user')),
                ('selected_tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamira_platform.Tool', verbose_name='the analysis selected tool by user')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('is_super_user', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='tool_request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamira_platform.User', verbose_name='the user'),
        ),
    ]
