# Generated by Django 2.1 on 2018-08-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamira_platform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='path',
        ),
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tool_request',
            name='id_request',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
